create schema if not exists AUTUACAO;
create schema if not exists PLATAFORMA;

drop table if exists AUTUACAO.NUMERO_PETICAO CASCADE CONSTRAINTS;
create table AUTUACAO.NUMERO_PETICAO (NUM_PETICAO bigint NOT NULL, ANO_PETICAO int NOT NULL, CONSTRAINT NUMERO_PETICAO_PK PRIMARY KEY (NUM_PETICAO, ANO_PETICAO));

drop table if exists AUTUACAO.NUMERO_PROCESSO CASCADE CONSTRAINTS;
create table AUTUACAO.NUMERO_PROCESSO (SIG_CLASSE varchar(10) NOT NULL, NUM_PROCESSO bigint NOT NULL, CONSTRAINT NUMERO_PROCESSO_PK PRIMARY KEY (SIG_CLASSE, NUM_PROCESSO));